### ISSUE TITLE
Death Arrows able to be crafted without Wither Skull

### ISSUE THREAD

**Issue by ericbarbwire** [2008Choco/AlchemicalArrows#1]
Hey, I'm running a Spigot 1.12.2 server 
When I craft a death arrow you can actually craft one without the need for a wither skull meaning you can just convert regular arrows into death arrows.
Here's an image of what I'm experiencing:
https://imgur.com/a/zPubZHW

Thank you very much for any help!
Here's my AA config as well: https://hastebin.com/bubazexula.http

**Comment by 2008Choco** [comment]
This was resolved in the `alchemical-arrows-3` branch and will be in the next release, Alchemical Arrows 3.0, upon the release of Spigot 1.13 Pre-1
