### ISSUE TITLE
Shot arrows behave like normal arrows, while summoned work as intended

### ISSUE THREAD

**Issue by octaharon** [2008Choco/AlchemicalArrows#11]
Can't get version 3.1.1 to work on Spigot 1.15.2. I don't see which plugin might interfere, except for worldguard (I have 7.1), but since there's an explicit perm for it, I assume it's not a problem. Permission manager is LuckPerms if matters.
So if I hit a player with /summonarrow, effects are applied as described in manual (I've tried a few), but if I /givearrow or create them, they all just do the same normal bow damage without any extras. Occurs regardless of permissions, both in Survival and Creative, both for Op and common players. One thing I've noticed though is that all particle effects are preserved, including fuse on TNT arrow, but the explosion won't happen. What can I do to collect more debugging information for you?

**Comment by 2008Choco** [comment]
I think at this point in development no additional information should be necessary. I plan on publishing an update in the near future which (unfortunately) will support 1.16.2+ and should address as many issue as I've come across recently.

**Comment by 2008Choco** [comment]
Closing due to a recent update which should have theoretically addressed this. If you are still having issues, ensure you have the `arrows.shoot.*` permission
