### ISSUE TITLE
Ghosting effect on items while in GUI

### ISSUE THREAD

**Issue by Stormystic** [2008Choco/AlchemicalArrows#13]
Items produce a ghosting/duplication effect when shift-clicking/moving them while inside some plugin called GUIs. E.g. /enderchest from essentials. /enderchest is the example used in the attached gif.

![Ghost](https://user-images.githubusercontent.com/55418600/114282117-fcb77300-9a0f-11eb-899e-bcb3c236051b.gif)

**Comment by 2008Choco** [comment]
Can you reproduce this in survival mode? Creative is very, very picky with how it handles inventories... If it's just a creative-exclusive issue I can better target a fix.

**Comment by Stormystic** [comment]
I was able to reproduce this in survival. I tried this on 1.16.5, latest version of paper with only Essentials & AA installed. Vanilla client. I was also able to reproduce this with a plugin called Minepacks. At some point I brought in another plugin called Shulker Backpacks which allows people to open Shulker Boxes via right-clicking, and for some reason the bug did not occur there.

**Comment by 2008Choco** [comment]
Alright, thank you! I will look into this. It may have to do with the legacy arrow conversion handler.
