### ISSUE TITLE
Spawn Arrows With Commands

### ISSUE THREAD

**Issue by APerson1738** [2008Choco/AlchemicalArrows#5]
I've Been Trying To Find A Way To Spawn The Arrows With Commands And I Dont Think It's Possible. It Would Be Great If You Added In This Feature. Thanks!

**Comment by 2008Choco** [comment]
A strange request, but I'm not necessarily _opposed_ to adding this. Is there any particular reason as to why you want to spawn the arrows by command?

**Comment by APerson1738** [comment]
My Server Has Bosses, And It Would Be Great To Implement The Arrows As An Attack Using Command Blocks

**Comment by 2008Choco** [comment]
Sounds fine to me. I'll see about adding it in the near future. I have to take this project out of beta anyways.

**Comment by APerson1738** [comment]
Thanks!

**Comment by 2008Choco** [comment]
https://github.com/2008Choco/AlchemicalArrows/commit/d8e6cb2fb0d4d0feaf73af8ff01dac2dc4c57a64
