### ISSUE TITLE
Infinity always on

### ISSUE THREAD

**Issue by TheRealShame** [2008Choco/AlchemicalArrows#6]
Even tho infinity is false in config, all arrows still have infinity on infinity bows

**Comment by 2008Choco** [comment]
I will take a look at this in preparation for the next update (likely for Minecraft 1.14)

**Comment by 2008Choco** [comment]
Please let me know if this issue was resolved in the latest release. I'm not certain as I never experienced the issue, although I'd very much appreciate hearing it from a user.
