### ISSUE TITLE
Arrows not working when players use it

### ISSUE THREAD

**Issue by SebasTheNinja** [2008Choco/AlchemicalArrows#7]
As the title says, i've been unable to make other players use the arrows correctly. I mean, they shoot them, but no effects are applied on the arrow nor the damaged entity, and they do have the permissions.

I'm playing on 1.14 by the way.

**Comment by 2008Choco** [comment]
I apologize for not getting to this issue but with as little information as I was given, I have nothing to work from. Arrows are working perfectly fine on a local copy, therefore I can only assume either permissions have not been properly applied or a plugin is interfering.
